project:
  type: website
  output-dir: docs

resources:
  - Resume/**

website:
  title: "Tadeh Peroomian"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
      - hobbies_and_goals.qmd
      - resume.qmd

format:
  html:
    theme:
      dark: solar
      light: minty
    css: styles.css
    toc: true