project:
  type: website
  output-dir: docs

website:
  title: "tadeh-peroomian.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Projects.qmd
      - Hobbies_and_Goals.qmd
      - Resume.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



